### ISSUE TITLE
TAlMemo Alcinoe Crashes App Android

### ISSUE THREAD

**Issue by jhonalone** [Zeus64/alcinoe#32]
I am trying to use a TAlMemo component in a real application but it does not work correctly.

In a very **simple** application you can see that it works perfectly

Using the same component in a real, more complex, app, you can see the **inner frame gets smaller**.
Making a **short tap** works perfectly.  But when  you do a **long tap** or **double tap**, then **CRASHES**  the application.

Both applications are in the same directory and use the same paths and use the same tools.
And both use exactly the same configuration at project/options.

Can you help me, please?

Best regards and thanks in advance.

![droid screen-1](https://user-images.githubusercontent.com/44949000/48317224-2d9cdf00-e5ef-11e8-9e72-a9be6ff674ff.png)
![droid screen-2](https://user-images.githubusercontent.com/44949000/48317225-2d9cdf00-e5ef-11e8-9d3d-dd54bb82e698.png)
![droid screen-3](https://user-images.githubusercontent.com/44949000/48317226-2d9cdf00-e5ef-11e8-8e26-efec2d169d06.png)
![design](https://user-images.githubusercontent.com/44949000/48317223-2d9cdf00-e5ef-11e8-90c7-c46af0a7fc0a.png)
![project-options1](https://user-images.githubusercontent.com/44949000/48317227-2d9cdf00-e5ef-11e8-9f04-f80b38e8affb.png)
![project-options2](https://user-images.githubusercontent.com/44949000/48317228-2e357580-e5ef-11e8-84c7-6650ed293f68.png)

**Comment by Zeus64** [comment]
Hi jhonalone, sorry for the delay

what version of android are you using? if you are using a version < android 6 then you need to include in your app some extra resource to Build the copy/past menu (else when you long tap and when the system will try to build the copy past menu you will have an error). it's because the copy/past menu was introduced in android 6, Before it's was a top bar (incompatible with delphi app).

you must include in de deployment (understand you must deploy) all the files located in Alcinoe\lib\jar\com.alcinoe\res\. If you don't want to do it manually you can use the tool Alcinoe\tools\DeployMan\

**Comment by jhonalone** [comment]
Hi. Zeus64.
I do not know if I understood correctly. Deplyment.exe is used for versions prior to Android 6.0.0? Or maybe you have to use it always?
Thank you very much for your help,

**Comment by Zeus64** [comment]
just to be sure the ALFmxControl demo work on your mobile phone ? can you try to reproduce in it the bug and just send me the source code that i can study it ?

**Comment by jhonalone** [comment]
And here is the complete directory with all the sources of the two programs. Maybe it will help you better.

[_source.zip](https://github.com/Zeus64/alcinoe/files/2577635/_source.zip)

**Comment by jhonalone** [comment]
Hi, Zeus64.
Do you have enough information? If you need anything else, please let me know.
Best regards.

**Comment by jhonalone** [comment]
Hi, Zeus64.
Do you have enough information? If you need anything else, please let me know.
Best regards.

**Comment by jhonalone** [comment]
I'm sorry, I hit the wrong button

**Comment by MyBuzzTechnologies** [comment]
I also have the same problem. This happens on Android 8.0, 8.1 and 9.0 devices due to it not being able to find the required value in the dimensions xml file. All resource files have been included in my app project along with the alcinoe.jar file generated by the build scripts.

I tried editing the .java source file to replace the reference with a static value and rebuilt the .jar file (and re-attached to my project) but it still crashes.

Could you suggest a fix for this please? We would really like to use the native memo in our app but this is stopping us.

The logcat reports the following as the cause:

11-20 16:10:59.504: E/AndroidRuntime(11610): FATAL EXCEPTION: main
11-20 16:10:59.504: E/AndroidRuntime(11610): Process: com.embarcadero.MemoFix, PID: 11610
11-20 16:10:59.504: E/AndroidRuntime(11610): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/alcinoe/R$dimen;
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at com.alcinoe.view.ALFloatingActionMode.<init>(ALFloatingActionMode.java:95)
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at com.alcinoe.widget.ALEditText.createFloatingActionMode(ALEditText.java:232)
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at com.alcinoe.widget.ALEditText.startActionMode(ALEditText.java:177)
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at com.alcinoe.widget.ALEditText.startActionMode(ALEditText.java:189)
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at android.widget.Editor.startSelectionActionModeInternal(Editor.java:2103)
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at android.widget.SelectionActionModeHelper.startActionMode(SelectionActionModeHelper.java:178)
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at android.widget.SelectionActionModeHelper.-android_widget_SelectionActionModeHelper-mthref-2(SelectionActionModeHelper.java:94)
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at android.widget.-$Lambda$tTszxdFZ0V9nXhnBpPsqeBMO0fw.$m$1(Unknown Source:6)
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at android.widget.-$Lambda$tTszxdFZ0V9nXhnBpPsqeBMO0fw.accept(Unknown Source:15)
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.onPostExecute(SelectionActionModeHelper.java:580)
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.onPostExecute(SelectionActionModeHelper.java:576)
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at android.os.AsyncTask.finish(AsyncTask.java:695)
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at android.os.Looper.loop(Looper.java:164)
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at java.lang.reflect.Method.invoke(Native Method)
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
11-20 16:10:59.504: E/AndroidRuntime(11610): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.alcinoe.R$dimen" on path: DexPathList[[zip file "/data/app/com.embarcadero.MemoFix-CBgXbL7Y_J0w0ZlsDHy37w==/base.apk"],nativeLibraryDirectories=[/data/app/com.embarcadero.MemoFix-CBgXbL7Y_J0w0ZlsDHy37w==/lib/arm, /data/app/com.embarcadero.MemoFix-CBgXbL7Y_J0w0ZlsDHy37w==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
11-20 16:10:59.504: E/AndroidRuntime(11610): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by jhonalone** [comment]
I have found out in which situation the first problem occurs. This means that the inner frame is not resized correctly when it is included in the "TScaledLayout" component. But I do not know how to solve it.
Can someone help me? Thanks.

**Comment by Zeus64** [comment]
can you try the last version with Rio? TALEdit/TalMemo was highly refactored to work in Rio with the new Zorder support (on android)

**Comment by jhonalone** [comment]
Thank you very much Zeus64 for your interest. But I'm sorry to tell you that the newest version of Delphi I have is Tokyo. I can not try it on Rio.
Best regards.

**Comment by Zeus64** [comment]
@jhonalone unfortunatly it's too hard to maintain tokyo + rio as they was a huge refactoring in Rio regarding Zorder. and anyway, in auguste, you will be unable to put anything in google play with Tokyo (because no android 64 support) so we are force to move to rio

**Comment by mirisu** [comment]
i am not complied alfmxcontrols,
[Exec Error] The command "D:\Rad Rio\alcinoe-master\tools\AddRJavaToClassesDex\AddRJavaToClassesDex.bat "D:\Rad Rio\alcinoe-master\demos\ALFmxControls\_source" "D:\Rad Rio\alcinoe-master\demos\ALFmxControls\Android\Debug\ALFmxControls.so" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.3\aapt.exe" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\platforms\android-28\android.jar" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.3\dx.bat" "C:\Program Files\Java\jdk1.8.0_60"&&D:\Rad Rio\alcinoe-master\demos\ALFmxControls\_source\..\..\..\tools\AddRJavaToClassesDex\AddRJavaToClassesDex.bat "D:\Rad Rio\alcinoe-master\demos\ALFmxControls\_source" "" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.3\aapt.exe" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\platforms\android-28\android.jar" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.3\dx.bat" "C:\Program Files\Java\jdk1.8.0_60"&&D:\Rad Rio\alcinoe-master\demos\ALFmxControls\_source\..\..\..\tools\AddRJavaToClassesDex\AddRJavaToClassesDex.bat "D:\Rad Rio\alcinoe-master\demos\ALFmxControls\_source" "D:\Rad Rio\alcinoe-master\demos\ALFmxControls\Android\Debug\ALFmxControls.so" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.3\aapt.exe" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\platforms\android-28\android.jar" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.3\dx.bat" "C:\Program Files\Java\jdk1.8.0_60"" exited with code 9009.

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
